// Code generated by logcopter-gen; DO NOT EDIT.

package wsm

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var log = logcopter.Package("go-go-golems.workspace-manager.pkg.wsm")
