// Code generated by logcopter-gen; DO NOT EDIT.

package runner

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var log = logcopter.Package("go-go-golems.workspace-manager.pkg.wsmjs.runner")
