package workflows

import (
	"context"
	"fmt"

	"github.com/go-go-golems/workspace-manager/pkg/wsm"
	"github.com/pkg/errors"
)

// CreateRequest captures workspace creation options.
type CreateRequest struct {
	Name         string
	Repos        []string
	Branch       string
	BranchPrefix string
	BaseBranch   string
	AgentSource  string
	DryRun       bool
}

// CreateResult captures workspace creation result details.
type CreateResult struct {
	Workspace           *wsm.Workspace
	FinalBranch         string
	AutoBranchGenerated bool
}

// CreateWorkflow orchestrates workspace creation.
type CreateWorkflow struct {
	manager *wsm.WorkspaceManager
}

// NewCreateWorkflow creates a create workflow service.
func NewCreateWorkflow() (*CreateWorkflow, error) {
	manager, err := wsm.NewWorkspaceManager()
	if err != nil {
		return nil, errors.Wrap(err, "failed to create workspace manager")
	}
	return &CreateWorkflow{manager: manager}, nil
}

// Create creates a workspace and returns the effective branch decision.
func (cw *CreateWorkflow) Create(ctx context.Context, req CreateRequest) (*CreateResult, error) {
	if len(req.Repos) == 0 {
		return nil, errors.New("no repositories specified. Use --repos flag or --interactive mode")
	}

	finalBranch, autoGenerated := BuildWorkspaceBranch(req.Name, req.Branch, req.BranchPrefix)

	workspace, err := cw.manager.CreateWorkspace(ctx, req.Name, req.Repos, finalBranch, req.BaseBranch, req.AgentSource, req.DryRun)
	if err != nil {
		return nil, errors.Wrap(err, "failed to create workspace")
	}

	return &CreateResult{
		Workspace:           workspace,
		FinalBranch:         finalBranch,
		AutoBranchGenerated: autoGenerated,
	}, nil
}

// BuildWorkspaceBranch computes the effective branch for a workspace request.
func BuildWorkspaceBranch(workspaceName, branch, branchPrefix string) (string, bool) {
	if branch != "" {
		return branch, false
	}
	prefix := branchPrefix
	if prefix == "" {
		prefix = "task"
	}
	return fmt.Sprintf("%s/%s", prefix, workspaceName), true
}
