// Code generated by logcopter-gen; DO NOT EDIT.

package js

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var log = logcopter.Package("go-go-golems.workspace-manager.cmd.wsm.cmds.js")
